<div classname="container"> 
  <div classname="bg-white rounded d-flex align-items-center justify-content-between" id="header"> 
    <button classname="btn btn-hide text-uppercase" type="button" data-toggle="collapse" data-target="#filterbar" aria-expanded="false" aria-controls="filterbar" id="filter-btn" onclick="changeBtnTxt()">
      <span classname="fas fa-angle-left" id="filter-angle"> 
        <span id="btn-txt">Hide filters</span> </span></button>
    <nav classname="navbar navbar-expand-lg navbar-light pl-lg-0 pl-auto">
      <button classname="navbar-toggler" type="button" data-toggle="collapse" data-target="#mynav" aria-controls="mynav" aria-expanded="false" aria-label="Toggle navigation" onclick="chnageIcon()" id="icon">
        <span classname="navbar-toggler-icon"> </span></button> <div classname="collapse navbar-collapse" id="mynav"> <ul classname="navbar-nav d-lg-flex align-items-lg-center"> <li classname="nav-item active"> <select name="sort" id="sort">
              <option value hidden selected>Sort by</option> <option value="price">Price</option> <option value="popularity">Popularity</option> 
              <option value="rating">Rating</option> </select> </li>
          <li classname="nav-item d-inline-flex align-items-center justify-content-between mb-lg-0 mb-3">
            <div classname="d-inline-flex align-items-center mx-lg-2" id="select2"> <div classname="pl-2">Products:</div> 
              <select name="pro" id="pro"> <option value="{18}">18</option> <option value="{19}">19</option>
                <option value="{20}">20</option> </select> </div> <div classname="font-weight-bold mx-2 result">18 from 200</div> 
          </li> <li classname="nav-item d-lg-none d-inline-flex"> </li> </ul> </div> </nav> <div classname="ml-auto mt-3 mr-2"> 
      <nav aria-label="Page navigation example"> <ul classname="pagination"> <li classname="page-item"> <a classname="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true" classname="font-weight-bold">&lt;</span> <span classname="sr-only">Previous</span> </a> </li> <li classname="page-item active">
            <a classname="page-link" href="#">1</a></li> <li classname="page-item"><a classname="page-link" href="#">..</a></li> <li classname="page-item"><a classname="page-link" href="#">24</a></li>
          <li classname="page-item"> <a classname="page-link" href="#" aria-label="Next"> <span aria-hidden="true" classname="font-weight-bold">&gt;</span>
              <span classname="sr-only">Next</span> </a> </li> </ul> </nav> </div> </div> <div id="content" classname="my-5">
    <div id="filterbar" classname="collapse"> <div classname="box border-bottom"> <div classname="form-group text-center"> <div classname="btn-group" data-toggle="buttons"> <label classname="btn btn-success form-check-label"> 
              <input classname="form-check-input" type="radio" /> Reset </label> <label classname="btn btn-success form-check-label active"> <input classname="form-check-input" type="radio" defaultchecked /> Apply </label> </div> </div> <div> <label classname="tick">New <input type="checkbox" defaultchecked="checked" /> <span classname="check"> </span></label>
        </div> <div> <label classname="tick">Sale <input type="checkbox" /> <span classname="check"> </span></label> </div> </div> <div classname="box border-bottom"> <div classname="box-label text-uppercase d-flex align-items-center">Outerwear
          <button classname="btn ml-auto" type="button" data-toggle="collapse" data-target="#inner-box" aria-expanded="false" aria-controls="inner-box" id="out" onclick="outerFilter()"> <span classname="fas fa-plus"> </span></button> 
        </div> <div id="inner-box" classname="collapse mt-2 mr-1"> <div classname="my-1"> <label classname="tick">Windbreaker <input type="checkbox" defaultchecked="checked" /> <span classname="check"> </span></label> </div> <div classname="my-1"> <label classname="tick">Jumpsuit <input type="checkbox" /> <span classname="check"> </span></label>
          </div> <div classname="my-1"> <label classname="tick">Jacket <input type="checkbox" /> <span classname="check"> </span></label> </div> <div classname="my-1"> <label classname="tick">Coat <input type="checkbox" /> <span classname="check"> </span></label> </div> <div classname="my-1"> <label classname="tick">Raincoat <input type="checkbox" /> <span classname="check"> 
              </span></label> </div> <div classname="my-1"> <label classname="tick">Handbag <input type="checkbox" defaultchecked /> <span classname="check"> </span></label> </div> <div classname="my-1"> <label classname="tick">Warm vest <input type="checkbox" /> <span classname="check"> </span></label> </div> <div classname="my-1"> <label classname="tick">Wallets <input type="checkbox" defaultchecked /> 
              <span classname="check"> </span></label> </div> </div> </div> <div classname="box border-bottom"> <div classname="box-label text-uppercase d-flex align-items-center">season <button classname="btn ml-auto" type="button" data-toggle="collapse" data-target="#inner-box2" aria-expanded="false" aria-controls="inner-box2"><span classname="fas fa-plus" /></button> 
        </div> <div id="inner-box2" classname="collapse mt-2 mr-1"> <div classname="my-1"> <label classname="tick">Spring <input type="checkbox" defaultchecked="checked" /> <span classname="check"> </span></label> </div> <div classname="my-1"> <label classname="tick">Summer <input type="checkbox" /> <span classname="check"> </span></label> 
          </div> <div classname="my-1"> <label classname="tick">Autumn <input type="checkbox" defaultchecked /> <span classname="check"> </span></label> </div> <div classname="my-1"> <label classname="tick">Winter <input type="checkbox" /> <span classname="check"> </span></label> </div> <div classname="my-1"> <label classname="tick">Rainy 
              <input type="checkbox" /> <span classname="check"> </span></label> </div> </div> </div> <div classname="box border-bottom"> <div classname="box-label text-uppercase d-flex align-items-center">price <button classname="btn ml-auto" type="button" data-toggle="collapse" data-target="#price" aria-expanded="false" aria-controls="price"><span classname="fas fa-plus" /></button> 
        </div> <div classname="collapse" id="price"> <div classname="middle"> <div classname="multi-range-slider"> <input type="range" id="input-left" min="{0}" max="{100}" defaultvalue="{10}" /> <input type="range" id="input-right" min="{0}" max="{100}" defaultvalue="{50}" /> <div classname="slider"> <div classname="track"> <div classname="range"> <div classname="thumb left"> <div classname="thumb right"> </div> </div> </div> <div classname="d-flex align-items-center justify-content-between mt-2"> <div> <span id="amount-left" classname="font-weight-bold"> uah </span></div> <div> <span id="amount-right" classname="font-weight-bold"> uah </span></div> </div> </div> </div> <div classname="box"> <div classname="box-label text-uppercase d-flex align-items-center">size <button classname="btn ml-auto" type="button" data-toggle="collapse" data-target="#size" aria-expanded="false" aria-controls="size"><span classname="fas fa-plus" /></button> </div>
                <div id="size" classname="collapse"> <div classname="btn-group d-flex align-items-center flex-wrap" data-toggle="buttons"> <label classname="btn btn-success form-check-label"> <input classname="form-check-input" type="checkbox" /> 80 </label> <label classname="btn btn-success form-check-label"> <input classname="form-check-input" type="checkbox" defaultchecked /> 92 </label> <label classname="btn btn-success form-check-label"> <input classname="form-check-input" type="checkbox" defaultchecked /> 102 </label> <label classname="btn btn-success form-check-label"> <input classname="form-check-input" type="checkbox" defaultchecked /> 104 </label> <label classname="btn btn-success form-check-label"> <input classname="form-check-input" type="checkbox" defaultchecked /> 106 </label> <label classname="btn btn-success form-check-label"> <input classname="form-check-input" type="checkbox" defaultchecked /> 108 </label> </div> </div> </div> </div> <div id="products"> <div classname="row mx-0"> 
                <div classname="col-lg-4 col-md-6"> <div classname="card d-flex flex-column align-items-center"> <div classname="product-name">Torn Jeans for Men</div> <div classname="card-img"> <img src="https://www.freepnglogos.com/uploads/jeans-png/jeans-mens-pants-cliparts-download-clip-art-37.png" alt /> </div> <div classname="card-body pt-5"> <div classname="text-muted text-center mt-auto">Available Colors</div> <div classname="d-flex align-items-center justify-content-center colors my-2"> <div classname="btn-group" data-toggle="buttons" data-tooltip="tooltip" data-placement="right" title="choose color"> <label classname="btn btn-red form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-blue form-check-label active"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-green form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-orange form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label>
                          <label classname="btn btn-pink form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> </div> </div> <div classname="d-flex align-items-center price"> <div classname="del mr-2"><span classname="text-dark">5500 uah</span></div> <div classname="font-weight-bold">4500 uah</div> </div> </div> </div> </div> <div classname="col-lg-4 col-md-6 pt-md-0 pt-3"> <div classname="card d-flex flex-column align-items-center"> <div classname="product-name">Nike Tshirts for Men</div> <div classname="card-img"> <img src="https://www.freepnglogos.com/uploads/t-shirt-png/t-shirt-png-printed-shirts-south-africa-20.png" alt height="{100}" id="shirt" /> </div> <div classname="text-muted text-center mt-auto">Available Sizes</div> <div id="avail-size"> <div classname="btn-group d-flex align-items-center flex-wrap" data-toggle="buttons"> <label classname="btn btn-success form-check-label"> <input classname="form-check-input" type="checkbox" /> 80 </label> <label classname="btn btn-success form-check-label"> <input classname="form-check-input" type="checkbox" defaultchecked /> 92 </label> <label classname="btn btn-success form-check-label"> <input classname="form-check-input" type="checkbox" defaultchecked /> 102 </label> <label classname="btn btn-success form-check-label"> <input classname="form-check-input" type="checkbox" defaultchecked /> 104 </label> <label classname="btn btn-success form-check-label"> <input classname="form-check-input" type="checkbox" defaultchecked /> 106 </label> <label classname="btn btn-success form-check-label"> <input classname="form-check-input" type="checkbox" defaultchecked /> 108 </label> </div> </div> <div classname="card-body pt-0"> <div classname="text-muted text-center mt-auto">Available Colors</div> <div classname="d-flex align-items-center justify-content-center colors my-2"> <div classname="btn-group" data-toggle="buttons" data-tooltip="tooltip" data-placement="right" title="choose color"> <label classname="btn btn-light border form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-blue form-check-label active"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-green form-check-label"> 
                            <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-orange form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-pink form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> </div> </div> <div classname="d-flex align-items-center price"> <div classname="del mr-2"><span classname="text-dark">5500 uah</span></div> <div classname="font-weight-bold">4500 uah</div> </div> </div> </div> </div> <div classname="col-lg-4 col-md-6 pt-lg-0 pt-md-4 pt-3"> <div classname="card d-flex flex-column align-items-center"> <div classname="product-name text-center">Casual Dress Belts For Men</div> <div classname="card-img"> <img src="https://www.freepnglogos.com/uploads/belts-png/casual-dress-belts-for-men-28.png" alt /> </div> <div classname="card-body pt-5"> <div classname="text-muted text-center mt-auto">Available Colors</div> <div classname="d-flex align-items-center justify-content-center colors my-2"> <div classname="btn-group" data-toggle="buttons" data-tooltip="tooltip" data-placement="right" title="choose color"> <label classname="btn btn-dark border form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-brown form-check-label active"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> </div> </div> <div classname="d-flex align-items-center justify-content-center price"> <div classname="font-weight-bold">500 uah</div> </div> </div> </div> </div> <div classname="col-lg-4 col-md-6 pt-md-4 pt-3"> <div classname="card d-flex flex-column align-items-center"> <div classname="product-name text-center">Footwear For Women</div> <div classname="card-img"> <img src="https://www.freepnglogos.com/uploads/women-shoes-png/download-women-shoes-png-image-png-image-pngimg-2.png" alt /> </div> <div classname="card-body pt-5"> <div classname="text-muted text-center mt-auto">Available Colors</div> <div classname="d-flex align-items-center justify-content-center colors my-2"> <div classname="btn-group" data-toggle="buttons" data-tooltip="tooltip" data-placement="right" title="choose color"> <label classname="btn btn-dark border form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-brown form-check-label active"> 
                            <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-pink form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-red form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> </div> </div> <div classname="d-flex align-items-center justify-content-center price"> <div classname="font-weight-bold">1500 uah</div> </div> </div> </div> </div> <div classname="col-lg-4 col-md-6 pt-md-4 pt-3"> <div classname="card d-flex flex-column align-items-center"> <div classname="product-name text-center">Nike Jogging shoes For Men</div> <div classname="card-img"> <img src="https://www.freepnglogos.com/uploads/shoes-png/find-your-perfect-running-shoes-26.png" alt /> </div> <div classname="card-body pt-5"> <div classname="text-muted text-center mt-auto">Available Colors</div> <div classname="d-flex align-items-center justify-content-center colors my-2"> <div classname="btn-group" data-toggle="buttons" data-tooltip="tooltip" data-placement="right" title="choose color"> <label classname="btn btn-dark border form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-pink form-check-label active"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-blue form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> <label classname="btn btn-orange form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> </div> </div> <div classname="d-flex align-items-center justify-content-center price"> <div classname="font-weight-bold">1200 uah</div> </div> </div> </div> </div> <div classname="col-lg-4 col-md-6 pt-md-4 pt-3"> <div classname="card d-flex flex-column align-items-center"> <div classname="product-name text-center">Leather Wallets For Men</div> <div classname="card-img"> <img src="https://www.freepnglogos.com/uploads/money-png/money-wallet-dollar-image-money-pictures-download-27.png" alt /> </div> <div classname="card-body pt-5"> <div classname="text-muted text-center mt-auto">Available Colors</div> <div classname="d-flex align-items-center justify-content-center colors my-2"> <div classname="btn-group" data-toggle="buttons" data-tooltip="tooltip" data-placement="right" title="choose color"> <label classname="btn btn-dark border form-check-label"> <input classname="form-check-input" type="radio" autoComplete="off" /> 
                          </label> <label classname="btn btn-brown form-check-label active"> <input classname="form-check-input" type="radio" autoComplete="off" /> </label> </div> </div> <div classname="d-flex align-items-center justify-content-center price"> <div classname="font-weight-bold">900 uah</div> </div> </div> </div> </div> </div> </div> </div> </div>
      </div></div></div></div>
